server:
  port: 8090
spring:
  application:
    name: seckill-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yun6
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.42.128:9300
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.42.128
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  redis:
    host: 192.168.42.128

  resources:
    add-mappings: true
    chain:
      enabled: true
      gzipped: true
      html-application-cache: true
    cache:
      period: 3600m
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
mybatis:
  type-aliases-package: com.leyou.seckill.pojo
  configuration:
    map-underscore-to-camel-case: true

leyou:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN