server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yun6
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.42.128
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.42.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    ip-address: 127.0.0.1
    prefer-ip-address: true

mybatis:
  type-aliases-package: com.leyou.user.pojo
ly:
  vc:
    exchange: "ly.sms.exchange"
    routingKey: "sms.verify.code"
    timeOut: 5
    codeLen: 6